#!/bin/bash

echo "Compile your project here"

pip3 install cryptography
pip3 install click
pip3 install dacite
pip3 install Django
pip3 install dnslib
pip3 install Flask
pip3 install falcon
pip3 install gunicorn
pip3 install PyCryptodome
pip3 install pyopenssl
pip3 install requests
pip3 install tornado
